spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/oncloud7/cloud-config.git
  application:
    name: config-server
server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/